export const MOSTRAR_PERSONAJES = 'MOSTRAR_PERSONAJES';
export const MOSTRAR_PERSONAJES_EXITO = 'MOSTRAR_PERSONAJES_EXITO';
export const MOSTRAR_PERSONAJES_ERROR = 'MOSTRAR_PERSONAJES_ERROR';

export const FILTRAR_PERSONAJES = 'FILTRAR_PERSONAJES';
